---

  - name: 4.5 Activate AppArmor (install) (Scored)
    apt: >
        name=apparmor
        state=present
    when: use_apparmor == True
    tags:
      - section4
      - section4.5

  - name: 4.5 Activate AppArmor (start) (Scored)
    service: >
        name=apparmor
        state=started
    when: use_apparmor == True
    tags:
      - section4
      - section4.5
      
  - name: 4.5 Activate AppArmor (fix profiles) (Scored)
    service: >
        name=rsyslog
        state=restarted
    when: use_apparmor == True
    tags:
      - section4
      - section4.5

  - name: 4.5 Activate AppArmor (Scored)
    command: apparmor_status
    register: aa_status_lines
    failed_when: '"0 profiles are loaded" in aa_status_lines.stdout_lines or "0 processes are in complain mode." not in aa_status_lines.stdout_lines or "0 processes are unconfined but have a profile defined." not in aa_status_lines.stdout_lines'
        # - '"0 processes are unconfined but have a profile defined." not in aa_status_lines.stdout_lines'
    changed_when: False
    when: use_apparmor == True
    tags:
      - section4
      - section4.5

  - name: 4.5 Activate AppArmor (enforce install) (Scored)
    apt: >
        name=apparmor-utils
        state=present
    when: use_apparmor == True
    tags:
      - section4
      - section4.5

  - name: 4.5 Activate AppArmor (enforce) (Scored)
    #shell: 'aa-enforce /etc/apparmor.d/*'
    shell: for profile in /etc/apparmor.d/*; do aa-enforce $profile; done
    register: aaenforce_rc
    failed_when: aaenforce_rc.rc == 1
    changed_when: False
    when: use_apparmor == True
    tags:
      - section4
      - section4.5
